### ISSUE TITLE
Preparación de materiales

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/github-tutorial#2]
Hola @pjmolina @ajpelu !

Muchas gracias por ofreceros a organizar el taller de Git & GitHub. Cómo va la preparación? Si vais subiendo material podemos ir comentando o ayudando en lo que se pueda

Abrazos

**Comment by Pakillo** [comment]
Dejo aquí algunas ideas que habíamos discutido (también con @ibartomeus) sobre el enfoque del taller por si sirven de ayuda:

- como tenemos hora y media, creo que lo mejor sería tener clase magistral de ~ 45-60 minutos, y luego 30-45 minutos para los que quieran probar en su laptop. 

- Se trata de una intro total, nivel 0. Básicamente, explicarles por qué es bueno usar un sistema de control de versiones, configurar git, introducir github, y hacer un par de commits, push-pull... Si llegamos a la parte de colaboración (i.e. 2 personas trabajando en código compartido) genial, pero yo me conformo con que la gente salga con la idea de que Git & GitHub son algo buenísimo y se le dén los primeros pasos para que puedan seguir usándolo tras el workshop.

Idealmente estaría enfocado a código de R, con Rstudio, que es lo que usan la inmensa mayoría de los ecólogos (e.g. http://happygitwithr.com/ y https://github.com/MangoTheCat/github-workshop#readme)

- En la clase magistral, creo que lo importante es que quede claro todo el potencial de usar Git & GitHub tanto para uso personal como colaborativo. Y que vean lo fácil que es usarlo desde Rstudio (a mí me gusta mucho Sourcetree, pero creo que para esta intro es mejor quedarse con Rstudio que es lo que usan casi todos)

**Comment by pjmolina** [comment]
Gracias @ajpelu y @Pakillo 
Creo que se ha podido seguir bien y no se nos han _"perdido"_ que era de lo que se trataba :-)
Os he hecho una _pull request_ con el material que vimos.  #3 

Saludos.

**Comment by Pakillo** [comment]
Wow está genial!! Muchísimas gracias @pjmolina

**Comment by ajpelu** [comment]
@pjmolina Gracias por las slides. Estuvo genial el workshop!! Abrazos

**Comment by pjmolina** [comment]
Gracias @Pakillo y @ajpelu Estamos en contacto.
